project_id = "gpcpovoikxgkgnabumlx"

[functions.artist-money-coach]
verify_jwt = true

[functions.beat-license-notification]
verify_jwt = true

[functions.delete-account]
verify_jwt = false

[functions.eventbrite-webhook]
verify_jwt = false

[functions.patreon-auth]
verify_jwt = false

[functions.patreon-posts]
verify_jwt = false

[functions.patreon-webhook]
verify_jwt = false

[functions.zapier-purchase-webhook]
verify_jwt = false

[functions.parse-disco-link]
verify_jwt = false

[functions.artist-track-download]
verify_jwt = false

[functions.submit-licensing-request]
verify_jwt = false

[functions.claim-migration-upgrade]
verify_jwt = false

[functions.create-tip-payment]
verify_jwt = false

[functions.create-stripe-connect-account]
verify_jwt = false

[functions.ingest-disco-track]
verify_jwt = false

[functions.create-store-checkout]
verify_jwt = false

[functions.stripe-membership-webhook]
verify_jwt = false
