project_id = "gpcpovoikxgkgnabumlx"

[functions.artist-money-coach]
verify_jwt = true

[functions.beat-license-notification]
verify_jwt = true

[functions.delete-account]
verify_jwt = false

[functions.patreon-auth]
verify_jwt = false

[functions.patreon-posts]
verify_jwt = false