// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-blog-posts.ts
var search_blog_posts_default = defineTool({
  name: "search_blog_posts",
  title: "Search blog posts",
  description: "Search published Modern Nostalgia Club blog posts by title, excerpt, or tag.",
  inputSchema: {
    query: z.string().trim().default("").describe("Optional keyword to match against title and excerpt."),
    limit: z.number().int().min(1).max(25).default(10).describe("Maximum number of posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabaseAnon();
    let builder = supabase.from("blog_posts").select("title, slug, excerpt, tags, author_name, published_at").eq("is_published", true).order("published_at", { ascending: false }).limit(limit);
    if (query) {
      builder = builder.or(`title.ilike.%${query}%,excerpt.ilike.%${query}%`);
    }
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List published Modern Nostalgia Club courses and the membership tier each one requires.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(25).describe("Maximum number of courses to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("courses").select("title, slug, description, min_tier, sort_order").eq("is_published", true).order("sort_order", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-submissions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_submissions_default = defineTool3({
  name: "list_my_submissions",
  title: "List my submissions",
  description: "List the signed-in member's Studio Floor submissions, their status, and any reviewer notes.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of submissions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("submissions").select("id, title, submission_type, status, reviewer_notes, created_at, reviewed_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-submission.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var create_submission_default = defineTool4({
  name: "create_submission",
  title: "Create a submission",
  description: "Create a Studio Floor submission for the signed-in member (sync review, catalog audit, branding, project proposal, audio mission, or producer mission).",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Title of the track or project being submitted."),
    submission_type: z4.enum([
      "sync-review",
      "catalog-audit",
      "branding",
      "project-proposal",
      "audio-mission",
      "producer-mission"
    ]).describe("The kind of review being requested."),
    disco_url: z4.string().trim().url().describe("Link to the music (DISCO or other private share link)."),
    notes: z4.string().trim().optional().describe("Optional context for the reviewer.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, submission_type, disco_url, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("submissions").insert({
      user_id: ctx.getUserId(),
      title,
      submission_type,
      disco_url,
      notes: notes ?? null
    }).select("id, title, submission_type, status, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { submission: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in member's Modern Nostalgia Club profile, including their membership tier.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("name, stage_name, username, bio, patreon_tier, profile_visibility, pro").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? null) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gpcpovoikxgkgnabumlx";
var mcp_default = defineMcp({
  name: "creative-economy-lab",
  title: "Creative Economy Lab",
  version: "0.1.0",
  instructions: "Tools for Modern Nostalgia Club (Creative Economy Lab). Browse published blog posts and courses, and \u2014 for the signed-in member \u2014 read their profile, list their Studio Floor submissions, and create new ones.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_blog_posts_default,
    list_courses_default,
    get_my_profile_default,
    list_my_submissions_default,
    create_submission_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
